import type { NextPage } from 'next';
import Head from 'next/head';
import { Banner, Header, Posts } from '../components';
import { sanityClient } from '../lib/sanity.server';
import { Post } from '../typings';

interface Props {
  posts: [Post];
}
const Home = ({ posts }: Props) => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6 justify-items-center">
        {posts.map((post) => (
          <Posts key={post._id} post={post} />
        ))}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const query = `*[_type == 'post']{
  _id,
  title,
  slug,
  author -> {
  name,
  image
},

  description,
  mainImage,
  slug

}`;

  const posts = await sanityClient.fetch(query);
  return {
    props: {
      posts,
    },
  };
}

export default Home;
